version: '3'
services:
  wp:
    build: .
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./html:/var/www/html
  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: